exp_name: str = Path(__file__).stem
seed: 1
torch_deterministic: true
cuda: true
capture_video: false
num_envs: 1

# Traffic environment arguments
traffic_density: 0.0

# Algorithm specific arguments
env_id: "S-Map"
total_timesteps: 1000000
buffer_size: int(1e6)
gamma: 0.99
tau: 0.005
batch_size: 256
learning_starts: 5e3
policy_lr: 3e-4
q_lr: 1e-3
policy_frequency: 2
gradient_steps: 1
target_network_frequency: 1
alpha: 0.2
autotune: True
compile: true
cudagraphs: true
measure_burnin: int = 3
