name: ✨ Feature
description: Propose a straightforward extension of rarlet functionality
title: "[Feature] <title>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is this a new feature in this repo?
      description: >
        To help deal with the volume of feature requests, we ask that you please check the following before submitting a new feature request.
      options:
        - label: I have searched the existing issues, and I could not find an existing issue for this feature
          required: true
  - type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Who will this benefit?
      description: |
        What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are suggesting!
    validations:
      required: false
