apiVersion: v1
kind: Pod
metadata:
  name: chang-acc-pod
spec:
  containers:
  - name: chang-luau
    image: gitlab-registry.nrp-nautilus.io/oliverc1622/luau:latest
    securityContext:
        runAsUser: 0
    command: ["/bin/bash", "-c"]
    args: 
      - |
        cd ~ && \
        git clone https://$(GIT_USERNAME):$(GIT_TOKEN)@github.com/oliverc1623/RARLET.git && cd RARLET && \
        cd Scenic && git submodule update --init && \
        git pull origin main && cd .. && \
        chmod +x nautilus/setup.sh && ./nautilus/setup.sh && \
        sleep infinity
    volumeMounts: 
    - mountPath: /pvcvolume
      name: elochang-volume
    - mountPath: /dev/shm
      name: dshm
    resources: 
      limits:
        memory: 32Gi
        cpu: "12"
        nvidia.com/gpu: 1
      requests: 
        memory: 16Gi
        cpu: "8"
        nvidia.com/gpu: 1
    env:
      - name: GIT_USERNAME
        valueFrom:
          secretKeyRef:
            name: github-auth
            key: username
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-auth
            key: token
  volumes: 
    - name: elochang-volume
      persistentVolumeClaim: 
        claimName: elochang-volume
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 16Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
              - NVIDIA-GeForce-RTX-3090
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - k8s-chase-ci-07.calit2.optiputer.net
  # tolerations: 
  # - key: "nautilus.io/reservation"
  #   operator: "Equal"
  #   value: "gilpin-lab"
  #   effect: "NoSchedule"
